# Generated by Django 2.0.3 on 2018-03-21 13:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('wikipedia_url', models.CharField(blank=True, max_length=50, null=True)),
                ('amazon_url', models.CharField(blank=True, max_length=50, null=True)),
                ('gutenburg_url', models.CharField(blank=True, max_length=50, null=True)),
                ('adelaide_url', models.CharField(blank=True, max_length=50, null=True)),
                ('copyright_expiration_us', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Author')),
            ],
            options={
                'ordering': ('author', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.TextField(unique=True)),
                ('isbn_13', models.TextField(unique=True)),
                ('publication_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ISBN'),
        ),
    ]
