# Generated by Django 2.0.3 on 2018-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksource',
            name='internal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
