# Generated by Django 2.0.3 on 2018-03-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='copyright_expiration_us',
            new_name='copyright_exp_us',
        ),
    ]
