# Generated by Django 2.0.3 on 2018-03-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_worksource_internal_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksource',
            unique_together={('work', 'source'), ('source', 'internal_id')},
        ),
    ]
