# Generated by Django 2.0.3 on 2018-03-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180321_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='gutenburg_url',
            new_name='gutenberg_url',
        ),
    ]
