# Generated by Django 2.0.3 on 2018-03-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180325_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookSource',
            new_name='WorkSource',
        ),
    ]
