# Generated by Django 2.0.3 on 2018-03-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180321_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copyright_expired',
            field=models.BooleanField(default=False),
        ),
    ]
