# Generated by Django 2.0.3 on 2018-03-26 10:56

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180325_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='genre',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
