# Generated by Django 2.0.3 on 2018-03-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180329_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksource',
            name='pdf_avail',
            field=models.BooleanField(default=True),
        ),
    ]
