# Generated by Django 2.0.3 on 2018-03-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_copyright_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='kobo_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
