# Generated by Django 2.0.3 on 2018-03-26 16:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180326_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='categories',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='work',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
