# Generated by Django 2.0.3 on 2018-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180330_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksource',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='worksource',
            name='epub_avail',
        ),
        migrations.RemoveField(
            model_name='worksource',
            name='kindle_avail',
        ),
        migrations.RemoveField(
            model_name='worksource',
            name='pdf_avail',
        ),
        migrations.AddField(
            model_name='worksource',
            name='epub_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worksource',
            name='kindle_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worksource',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worksource',
            name='purchase_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
