# Generated by Django 2.0.3 on 2018-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180330_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksource',
            name='book_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='epub_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='kindle_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='purchase_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
