# Generated by Django 2.0.3 on 2018-03-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180331_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdelaideWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_first', models.CharField(max_length=50)),
                ('author_last', models.CharField(max_length=50)),
                ('translator', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='adelaidework',
            unique_together={('author_last', 'title')},
        ),
    ]
