# Generated by Django 2.0.3 on 2018-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180331_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelaidework',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
