# Generated by Django 2.0.3 on 2018-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_work_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GutenbergWork',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('author_first', models.CharField(max_length=100)),
                ('author_last', models.CharField(max_length=100)),
                ('translator', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
