# Generated by Django 2.0.3 on 2018-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_isbn_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('title', 'author')},
        ),
        migrations.AddField(
            model_name='work',
            name='additional_authors',
            field=models.ManyToManyField(related_name='works_as_additional', to='main.Author'),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='book_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='epub_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='kindle_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='purchase_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('title', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='worksource',
            unique_together={('work', 'source')},
        ),
    ]
