# Generated by Django 2.0.3 on 2018-04-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_isbn_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksource',
            name='book_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='epub_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='kindle_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worksource',
            name='purchase_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
