# Generated by Django 2.0.3 on 2018-04-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180402_1251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksource',
            unique_together={('work', 'source')},
        ),
    ]
