# Generated by Django 2.0.3 on 2018-04-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180402_1753'),
        ('main', '0022_auto_20180403_1845'),
    ]

    operations = [
    ]
