# Generated by Django 2.0.3 on 2018-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_merge_20180403_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='adelaidework',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adelaidework',
            name='author_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adelaidework',
            name='url',
            field=models.CharField(default='delete', max_length=150),
            preserve_default=False,
        ),
    ]
