# Generated by Django 2.0.4 on 2018-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180407_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
