# Generated by Django 2.0.4 on 2018-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_work_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gutenbergwork',
            name='author_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
