# Generated by Django 2.0.4 on 2018-04-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180413_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('title_query', models.CharField(blank=True, max_length=200, null=True)),
                ('author_query', models.CharField(blank=True, max_length=200, null=True)),
                ('works', models.ManyToManyField(related_name='reports', to='main.Work')),
            ],
        ),
    ]
