# Generated by Django 2.0.4 on 2018-04-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='works',
        ),
    ]
