# Generated by Django 2.0.4 on 2018-04-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_contactmessage_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksource',
            name='internal_id_str',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='additional_authors',
            field=models.ManyToManyField(blank=True, related_name='works_as_additional', to='main.Author'),
        ),
    ]
